# Generated by Django 6.0.1 on 2026-02-09 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_populate_courses_lectures'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='level',
            field=models.PositiveIntegerField(default=0, help_text='Current level calculated from XP.'),
        ),
        migrations.AddField(
            model_name='member',
            name='xp',
            field=models.PositiveIntegerField(default=0, help_text='Total experience points earned by the user.'),
        ),
        migrations.CreateModel(
            name='LectureQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='members.lecture')),
            ],
            options={
                'ordering': ['lecture_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MemberLectureProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('answered_correctly', models.BooleanField(default=False)),
                ('xp_awarded', models.PositiveIntegerField(default=0)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_progress', to='members.lecture')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_progress', to='members.member')),
            ],
            options={
                'unique_together': {('member', 'lecture')},
            },
        ),
    ]
