# Generated by Django 6.0.1 on 2026-02-20 13:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_memberquizattempt_memberachievement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device', models.CharField(blank=True, default='Unknown device', max_length=255)),
                ('location', models.CharField(blank=True, default='Unknown location', max_length=255)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('logged_in_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('logged_out_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-logged_in_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light'), ('system', 'System')], default='dark', max_length=10)),
                ('accent_color', models.CharField(default='#38bdf8', max_length=7)),
                ('compact_mode', models.BooleanField(default=False)),
                ('font_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10)),
                ('animations_enabled', models.BooleanField(default=True)),
                ('notify_course_updates', models.BooleanField(default=True)),
                ('notify_new_lectures', models.BooleanField(default=True)),
                ('notify_email', models.BooleanField(default=True)),
                ('notify_in_app', models.BooleanField(default=True)),
                ('notify_telegram', models.BooleanField(default=False)),
                ('profile_visibility', models.CharField(choices=[('everyone', 'Everyone'), ('registered', 'Registered users'), ('only_me', 'Only me')], default='everyone', max_length=20)),
                ('analytics_tracking', models.BooleanField(default=True)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('two_factor_secret', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
